[package]
name = "gistory"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "*"
clap = { version = "*", features = ["derive"] }
git2 = "*"
chrono = { version = "*", features = ["serde"] }
chrono-english = "0.1"
ratatui = "*"
crossterm = "*"
